CREATE TABLE IF NOT EXISTS Provider(
    ID VARCHAR(40) PRIMARY KEY,
    URL VARCHAR(50) NOT NULL,
    ChannelRefID VARCHAR(40) NOT NULL,
    Name VARCHAR(80) NOT NULL);

CREATE TYPE status AS ENUM ('YES','NO');

CREATE TABLE IF NOT EXISTS Message(
    ID VARCHAR(40) PRIMARY KEY,
    Message VARCHAR(100) NOT NULL,
    Number VARCHAR(20) NOT NULL,
    Transactional VARCHAR(50) NOT NULL,
    Status status NOT NULL DEFAULT 'NO',
    Delivered_time TIMESTAMP);